name: Jett
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70518
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0995D'
    - '#534030'
    - '#20150C'
    - '#87B4BD'
    - '#5C7777'
  brandStrength: 0.1863799
  lightness: 0.4121864
  saturation: 0.6648746
  rhythmicContrast: 0.06996112
purpose: []
