name: Jett
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70518
title: "My website's better than your honor student."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0bcbb'
    - '#0a0b10'
    - '#484848'
    - '#388693'
    - '#eae8eb'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
